# version: '3.4' # needed for backward compatibility. informative only.

services:
  goapi:
    image: goapi
    volumes:
      - type: bind
        source: /Users/alexan/Desktop/repos/scratch/go-api/my-bind-mnt/data.json
        target: /home/alex/code/data.json
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:10000
