# version: '3.4' # needed for backward compatibility. informative only.

services:
  goapi:
    image: goapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:10000
